// <auto-generated />
using System;
using AnimalConnect.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalConnect.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209151811_RefactorClinicasYHorarios")]
    partial class RefactorClinicasYHorarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EdadAproximada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaUltimaRenovacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("UbicacionLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("UbicacionLon")
                        .HasColumnType("double precision");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdEstado");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.AnimalAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AtributoId");

                    b.ToTable("AnimalAtributos");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Campania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("UbicacionLat")
                        .HasColumnType("double precision");

                    b.Property<double>("UbicacionLon")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Campanias");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDeTurno")
                        .HasColumnType("boolean");

                    b.Property<string>("HorariosEstructurados")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PerfilVeterinarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilVeterinarioId");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.HorarioClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("HoraApertura")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HoraCierre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("HorariosClinicas");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilesAdoptantes");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilCiudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text");

                    b.Property<double>("LatitudHome")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudHome")
                        .HasColumnType("double precision");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesCiudadanos");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilMunicipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("LatitudCentro")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudCentro")
                        .HasColumnType("double precision");

                    b.Property<string>("NombreMunicipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RadioCoberturaKm")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesMunicipios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilVeterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoVerificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text");

                    b.Property<string>("MatriculaProfesional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesVeterinarios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PreferenciaAdoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("integer");

                    b.Property<int>("Importancia")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilAdoptanteId")
                        .HasColumnType("integer");

                    b.Property<int>("ValorPreferido")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilAdoptanteId");

                    b.ToTable("PreferenciasAdoptantes");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Especie");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.AnimalAtributo", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Animal", "Animal")
                        .WithMany("Atributos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Atributo");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Clinica", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.PerfilVeterinario", "Dueño")
                        .WithMany("Clinicas")
                        .HasForeignKey("PerfilVeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Comentario", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.HorarioClinica", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Clinica", "Clinica")
                        .WithMany("Horarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilCiudadano", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithOne("PerfilCiudadano")
                        .HasForeignKey("AnimalConnect.Backend.Models.PerfilCiudadano", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilMunicipio", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithOne("PerfilMunicipio")
                        .HasForeignKey("AnimalConnect.Backend.Models.PerfilMunicipio", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilVeterinario", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithOne("PerfilVeterinario")
                        .HasForeignKey("AnimalConnect.Backend.Models.PerfilVeterinario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Post", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PreferenciaAdoptante", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.PerfilAdoptante", "PerfilAdoptante")
                        .WithMany("Preferencias")
                        .HasForeignKey("PerfilAdoptanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("PerfilAdoptante");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.Navigation("Atributos");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Clinica", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.Navigation("Preferencias");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilVeterinario", b =>
                {
                    b.Navigation("Clinicas");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Post", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Usuario", b =>
                {
                    b.Navigation("PerfilCiudadano");

                    b.Navigation("PerfilMunicipio");

                    b.Navigation("PerfilVeterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
