// <auto-generated />
using System;
using AnimalConnect.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalConnect.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EdadAproximada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("UbicacionLat")
                        .HasColumnType("float");

                    b.Property<double?>("UbicacionLon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdEstado");

                    b.ToTable("Animales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Activo y juguetón.",
                            EdadAproximada = "2 años",
                            FechaPublicacion = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEspecie = 1,
                            IdEstado = 1,
                            ImagenUrl = "http://127.0.0.1:5269/uploads/PerroAdoptar1.png",
                            Nombre = "Rocky",
                            UbicacionLat = -37.994,
                            UbicacionLon = -61.353000000000002
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Muy tranquila.",
                            EdadAproximada = "4 años",
                            FechaPublicacion = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEspecie = 2,
                            IdEstado = 1,
                            ImagenUrl = "http://127.0.0.1:5269/uploads/GatoAdoptar1.png",
                            Nombre = "Mishi",
                            UbicacionLat = -37.996000000000002,
                            UbicacionLon = -61.354999999999997
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Perdido en plaza.",
                            EdadAproximada = "Viejito",
                            FechaPublicacion = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEspecie = 1,
                            IdEstado = 2,
                            ImagenUrl = "http://127.0.0.1:5269/uploads/PerroPerdido2.png",
                            Nombre = "Tobi",
                            UbicacionLat = -37.991999999999997,
                            UbicacionLon = -61.350999999999999
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.AnimalAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("AtributoId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AtributoId");

                    b.ToTable("AnimalAtributos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            AtributoId = 1,
                            Valor = 5
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 1,
                            AtributoId = 2,
                            Valor = 1
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 2,
                            AtributoId = 1,
                            Valor = 1
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 2,
                            AtributoId = 2,
                            Valor = 0
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Atributos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Nivel de Energía",
                            Tipo = "Escala"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Requiere Patio",
                            Tipo = "Booleano"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tolera Niños",
                            Tipo = "Booleano"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Tolera Gatos",
                            Tipo = "Booleano"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Tiempo de Atención",
                            Tipo = "Escala"
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Campania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("UbicacionLat")
                        .HasColumnType("float");

                    b.Property<double>("UbicacionLon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Campanias");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Especies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gato"
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "En Adopción"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Perdido"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Encontrado"
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilesAdoptantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TelefonoContacto = "111-222",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            TelefonoContacto = "333-444",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PreferenciaAdoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtributoId")
                        .HasColumnType("int");

                    b.Property<int>("Importancia")
                        .HasColumnType("int");

                    b.Property<int>("PerfilAdoptanteId")
                        .HasColumnType("int");

                    b.Property<int>("ValorPreferido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("PerfilAdoptanteId");

                    b.ToTable("PreferenciasAdoptantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtributoId = 1,
                            Importancia = 5,
                            PerfilAdoptanteId = 1,
                            ValorPreferido = 5
                        },
                        new
                        {
                            Id = 2,
                            AtributoId = 2,
                            Importancia = 3,
                            PerfilAdoptanteId = 1,
                            ValorPreferido = 1
                        },
                        new
                        {
                            Id = 3,
                            AtributoId = 1,
                            Importancia = 5,
                            PerfilAdoptanteId = 2,
                            ValorPreferido = 1
                        },
                        new
                        {
                            Id = 4,
                            AtributoId = 2,
                            Importancia = 5,
                            PerfilAdoptanteId = 2,
                            ValorPreferido = 0
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "admin",
                            PasswordHash = "admin123",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            NombreUsuario = "juan",
                            PasswordHash = "1234",
                            Rol = "Ciudadano"
                        },
                        new
                        {
                            Id = 3,
                            NombreUsuario = "maria",
                            PasswordHash = "1234",
                            Rol = "Ciudadano"
                        });
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.AnimalAtributo", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Animal", "Animal")
                        .WithMany("Atributos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Atributo");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PreferenciaAdoptante", b =>
                {
                    b.HasOne("AnimalConnect.Backend.Models.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalConnect.Backend.Models.PerfilAdoptante", "PerfilAdoptante")
                        .WithMany("Preferencias")
                        .HasForeignKey("PerfilAdoptanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("PerfilAdoptante");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.Animal", b =>
                {
                    b.Navigation("Atributos");
                });

            modelBuilder.Entity("AnimalConnect.Backend.Models.PerfilAdoptante", b =>
                {
                    b.Navigation("Preferencias");
                });
#pragma warning restore 612, 618
        }
    }
}
